In [56]:
# Imports
import sys
import os

sys.path.append(os.path.abspath(".."))
import numpy as np

from numcompute.io import load_csv
from numcompute.preprocessing import Imputer, StandardScaler, OneHotEncoder
from numcompute.sort_search import topk, binary_search
from numcompute.rank import rank, percentile
from numcompute.stats import mean, std, histogram, quantile
from numcompute.metrics import accuracy, f1_score, mse
from numcompute.optim import grad, jacobian
from numcompute.pipeline import Pipeline
from numcompute.benchmarking import benchmark

In [57]:
# Loading the data
X = load_csv("../test.csv", skip_header=1)
print("Raw Data:")
print(X)

Raw Data:
[['Alice' '25' '50000']
 ['Bob' nan '60000']
 ['Charlie' '30' nan]]


In [66]:
# Preprocessing Pipeline
pipe = Pipeline(
    [("impute", Imputer()), ("scale", StandardScaler()), ("encode", OneHotEncoder())]
)

X_processed = pipe.fit_transform(X)

print("Processed Data:")
print(X_processed)

Processed Data:
[[ 1.          0.          0.         -1.22474487 -1.22474487]
 [ 0.          1.          0.          0.          1.22474487]
 [ 0.          0.          1.          1.22474487  0.        ]]


In [67]:
# Steps of pipeline
I = Imputer().fit_transform(X)
print(I)
S = StandardScaler().fit_transform(I)
print(S)
O = OneHotEncoder().fit_transform(S)
print(O)

[['Alice' '25' '50000']
 ['Bob' np.float64(27.5) '60000']
 ['Charlie' '30' np.float64(55000.0)]]
[['Alice' -1.224744871391589 -1.2247448713915892]
 ['Bob' 0.0 1.2247448713915892]
 ['Charlie' 1.224744871391589 0.0]]
[[ 1.          0.          0.         -1.22474487 -1.22474487]
 [ 0.          1.          0.          0.          1.22474487]
 [ 0.          0.          1.          1.22474487  0.        ]]


In [60]:
# Using the topk and binary search functions
arr = np.array([10, 5, 20, 15])

vals, idx = topk(arr, 2)
print("Top 2 values:", vals)

i, found = binary_search(np.sort(arr), 15)
print("Binary search (15):", i, found)

Top 2 values: [20 15]
Binary search (15): 2 True


In [61]:
# Using the rank and percentile functions
data = np.array([10, 20, 20, 30])

print("Ranks (average):", rank(data, method="average"))
print("50th percentile:", percentile(data, 50))

Ranks (average): [1.  2.5 2.5 4. ]
50th percentile: 20.0


In [62]:
# Using the statistics functions
arr = np.array([1, 2, 3, np.nan])

print("Mean:", mean(arr))
print("Std:", std(arr))

counts, edges = histogram(np.array([1, 2, 2, 3, 4]), bins=3)

print("Histogram counts:", counts)
print("Quantile (0.5):", quantile(np.array([10, 20, 30, 40]), 0.5))

Mean: 2.0
Std: 0.816496580927726
Histogram counts: [1 2 2]
Quantile (0.5): 25.0


In [63]:
# Using the metrics functions
y_true = np.array([1, 0, 1, 1])
y_pred = np.array([1, 0, 0, 1])

print("Accuracy:", accuracy(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))
print("MSE:", mse([1, 2], [1, 3]))

Accuracy: 0.75
F1 Score: 0.7894736744044323
MSE: 0.5


In [64]:
# Usint the gradient function and jacobian fuction
def f(x):
    return x[0] ** 2 + x[1] ** 2


g = grad(f, np.array([2.0, 3.0]))

print("Gradient:", g)

def g(x):
    return np.array([
        x[0] ** 2 + x[1],
        x[0] + x[1] ** 2
    ])

j = jacobian(g, np.array([2.0, 3.0]))

print("Jacobian:", j)

Gradient: [4. 6.]
Jacobian: [[4. 1.]
 [1. 6.]]


In [65]:
# Using the benchmark function
def loop_sum(x):
    total = 0
    for i in x:
        total += i
    return total


def vectorized_sum(x):
    return np.sum(x)


x = np.random.rand(1000000)

benchmark("Sum", vectorized_sum, loop_sum, x)

print()
print("Entire module executed successfully!")


Sum Benchmark
------------------------------
Vectorized: 0.003069 sec
Loop:       0.183348 sec
Speedup:    59.73x

Entire module executed successfully!
